INSERT INTO constraint_categories (id, name, description) VALUES (1, 'Environment, Landscape & Natural Heritage', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (2, 'Cultural Heritage', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (3, 'Surface water & flooding', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (4, 'Infrastructure', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (5, 'Aviation', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (6, 'Peat', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (7, 'Marine', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (8, 'Land Classification', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (9, 'Other', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (10, 'Unknown', NULL);
INSERT INTO constraint_categories (id, name, description) VALUES (11, 'Recreation', NULL);