# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jcampbell\OneDrive - EDF Renouvelables\Documents\python_projects\constraints_db\src\gui\qt5\dlgs\qt_designer\qt_files//add_development_constraint.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDevelopmentConstraintDlg(object):
    def setupUi(self, AddDevelopmentConstraintDlg):
        AddDevelopmentConstraintDlg.setObjectName("AddDevelopmentConstraintDlg")
        AddDevelopmentConstraintDlg.resize(640, 480)
        self.formLayout = QtWidgets.QFormLayout(AddDevelopmentConstraintDlg)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.NameLE = QtWidgets.QLineEdit(AddDevelopmentConstraintDlg)
        self.NameLE.setObjectName("NameLE")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.NameLE)
        self.label_3 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.AbbreviationLE = QtWidgets.QLineEdit(AddDevelopmentConstraintDlg)
        self.AbbreviationLE.setObjectName("AbbreviationLE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.AbbreviationLE)
        self.label_4 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.TableNameLE = QtWidgets.QLineEdit(AddDevelopmentConstraintDlg)
        self.TableNameLE.setObjectName("TableNameLE")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.TableNameLE)
        self.label_2 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.CategoryCB = QtWidgets.QComboBox(AddDevelopmentConstraintDlg)
        self.CategoryCB.setObjectName("CategoryCB")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.CategoryCB)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddDevelopmentConstraintDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.OnshoreWindPriorityLevelCB = QtWidgets.QComboBox(AddDevelopmentConstraintDlg)
        self.OnshoreWindPriorityLevelCB.setObjectName("OnshoreWindPriorityLevelCB")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.OnshoreWindPriorityLevelCB)
        self.label_5 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.SolarPriorityLevelCB = QtWidgets.QComboBox(AddDevelopmentConstraintDlg)
        self.SolarPriorityLevelCB.setObjectName("SolarPriorityLevelCB")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.SolarPriorityLevelCB)
        self.label_6 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.BatteryPriorityLevelCB = QtWidgets.QComboBox(AddDevelopmentConstraintDlg)
        self.BatteryPriorityLevelCB.setObjectName("BatteryPriorityLevelCB")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.BatteryPriorityLevelCB)
        self.label_7 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.DescriptionTE = QtWidgets.QTextEdit(AddDevelopmentConstraintDlg)
        self.DescriptionTE.setObjectName("DescriptionTE")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.DescriptionTE)
        self.NotesTE = QtWidgets.QTextEdit(AddDevelopmentConstraintDlg)
        self.NotesTE.setObjectName("NotesTE")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.NotesTE)
        self.label_8 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(AddDevelopmentConstraintDlg)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem)

        self.retranslateUi(AddDevelopmentConstraintDlg)
        self.buttonBox.accepted.connect(AddDevelopmentConstraintDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(AddDevelopmentConstraintDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddDevelopmentConstraintDlg)

    def retranslateUi(self, AddDevelopmentConstraintDlg):
        _translate = QtCore.QCoreApplication.translate
        AddDevelopmentConstraintDlg.setWindowTitle(_translate("AddDevelopmentConstraintDlg", "Dialog"))
        self.label.setText(_translate("AddDevelopmentConstraintDlg", "Name"))
        self.label_3.setText(_translate("AddDevelopmentConstraintDlg", "Abbreviation"))
        self.AbbreviationLE.setPlaceholderText(_translate("AddDevelopmentConstraintDlg", "Optional"))
        self.label_4.setText(_translate("AddDevelopmentConstraintDlg", "Table Name"))
        self.TableNameLE.setPlaceholderText(_translate("AddDevelopmentConstraintDlg", "Defaults to name if left blank"))
        self.label_2.setText(_translate("AddDevelopmentConstraintDlg", "Category"))
        self.label_5.setText(_translate("AddDevelopmentConstraintDlg", "Onshore Wind Priority Level"))
        self.label_6.setText(_translate("AddDevelopmentConstraintDlg", "Solar Priority Level"))
        self.label_7.setText(_translate("AddDevelopmentConstraintDlg", "Battery Priority Level"))
        self.label_8.setText(_translate("AddDevelopmentConstraintDlg", "Description"))
        self.label_9.setText(_translate("AddDevelopmentConstraintDlg", "Notes"))
