# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jcampbell\OneDrive - EDF Renouvelables\Documents\python_projects\constraints_db\src\gui\qt5\dlgs\qt_designer\qt_files//select_geom_type.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectGeomTypeDlg(object):
    def setupUi(self, SelectGeomTypeDlg):
        SelectGeomTypeDlg.setObjectName("SelectGeomTypeDlg")
        SelectGeomTypeDlg.resize(640, 480)
        self.formLayout = QtWidgets.QFormLayout(SelectGeomTypeDlg)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SelectGeomTypeDlg)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.GeometryTypeCB = QtWidgets.QComboBox(SelectGeomTypeDlg)
        self.GeometryTypeCB.setObjectName("GeometryTypeCB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.GeometryTypeCB)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectGeomTypeDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)

        self.retranslateUi(SelectGeomTypeDlg)
        self.buttonBox.accepted.connect(SelectGeomTypeDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(SelectGeomTypeDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectGeomTypeDlg)

    def retranslateUi(self, SelectGeomTypeDlg):
        _translate = QtCore.QCoreApplication.translate
        SelectGeomTypeDlg.setWindowTitle(_translate("SelectGeomTypeDlg", "Dialog"))
        self.label.setText(_translate("SelectGeomTypeDlg", "Select geometry type for new layer"))
