"""added not null constraint

Revision ID: a7586cc17d7d
Revises: e273ce2bbf5e
Create Date: 2024-02-27 10:22:45.637636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = 'a7586cc17d7d'
down_revision: Union[str, None] = 'e273ce2bbf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraint_layers', 'data_accessed_or_created',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraint_layers', 'data_accessed_or_created',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
