"""Added battery priority level column to development_constraint table

Revision ID: c9bb266ea5cb
Revises: 02672f509261
Create Date: 2024-03-13 14:46:45.140639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = 'c9bb266ea5cb'
down_revision: Union[str, None] = '02672f509261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('development_constraints', sa.Column('battery_priority_level_id', sa.Integer(), server_default='5', nullable=False))
    op.create_foreign_key(None, 'development_constraints', 'priority_levels', ['battery_priority_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'development_constraints', type_='foreignkey')
    op.drop_column('development_constraints', 'battery_priority_level_id')
    # ### end Alembic commands ###
