"""deleted admin levels table

Revision ID: e273ce2bbf5e
Revises: 03ddfc3aabeb
Create Date: 2024-02-27 10:10:01.570672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = 'e273ce2bbf5e'
down_revision: Union[str, None] = '03ddfc3aabeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('administrative_areas_administrative_level_id_fkey', 'administrative_areas', type_='foreignkey')
    op.drop_column('administrative_areas', 'administrative_level_id')
    op.drop_constraint('constraint_layers_administrative_level_id_fkey', 'constraint_layers', type_='foreignkey')
    op.drop_column('constraint_layers', 'administrative_level_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constraint_layers', sa.Column('administrative_level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('constraint_layers_administrative_level_id_fkey', 'constraint_layers', 'administrative_levels', ['administrative_level_id'], ['id'])
    op.add_column('administrative_areas', sa.Column('administrative_level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('administrative_areas_administrative_level_id_fkey', 'administrative_areas', 'administrative_levels', ['administrative_level_id'], ['id'])
    # ### end Alembic commands ###
