"""added abb column to admin areas

Revision ID: fefd28a82af6
Revises: a7586cc17d7d
Create Date: 2024-02-28 08:48:04.778901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = 'fefd28a82af6'
down_revision: Union[str, None] = 'a7586cc17d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrative_areas', sa.Column('abbreviation', sa.TEXT(), nullable=True))
    op.create_unique_constraint(None, 'administrative_areas', ['abbreviation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'administrative_areas', type_='unique')
    op.drop_column('administrative_areas', 'abbreviation')
    # ### end Alembic commands ###
