name: Test Python Package using Conda

on:
  [push] 

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        which qgis

    - name: Add QGIS to Conda PYTHONPATH
      run: |
        site_packages_path=$(python -c "import site; print(''.join(site.getsitepackages()))")
        echo "site packages directory: $site_packages_path"
        qgis_python_path=$(dirname $(which qgis))/../share/qgis/python
        echo "QGIS python directory: $qgis_python_path"
        touch ${site_packages_path}/conda.pth
        echo "${qgis_python_path}" > ${site_packages_path}/conda.pth
        python_path=$(python -c "import sys; print(sys.path)")
        echo "python path: $python_path"
        qgis_version=$(python -c "import qgis; print(qgis.core.Qgis.QGIS_VERSION)")
        echo "QGIS version: $qgis_version"


    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


    - name: Test with pytest
      run: |
        pytest

    - name: Run MyPy
      run: |
        mypy src --strict

    - name: Build Docs
      run: |
        sphinx-apidoc -o docs/source src/db
        sphinx-build -M html docs/source docs/build -W

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html

